//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bangDiemChiTiet
    {
        public int Id { get; set; }
        public string mssv { get; set; }
        public string STT { get; set; }
        public string maHocPhan { get; set; }
        public string tenHocPhan { get; set; }
        public string soTC { get; set; }
        public string lanHoc { get; set; }
        public string lanThi { get; set; }
        public string diemThu { get; set; }
        public string laDiemTongKetMon { get; set; }
        public string danhGia { get; set; }
        public string tp1 { get; set; }
        public string tp2 { get; set; }
        public string thi { get; set; }
        public byte[] tkhp { get; set; }
        public string tkhp2 { get; set; }
    }
}
