//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chungChi
    {
        public int Id { get; set; }
        public string mssv { get; set; }
        public string STT { get; set; }
        public string chungChi1 { get; set; }
        public string diem { get; set; }
        public string xepLoai { get; set; }
    }
}
