//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class danhSachKhoanPhaiDong
    {
        public int Id { get; set; }
        public string STT { get; set; }
        public string hocKy { get; set; }
        public string soTC { get; set; }
        public string soTien { get; set; }
        public string mienGiam { get; set; }
        public string hocLai { get; set; }
        public string phaiDong { get; set; }
        public string mssv { get; set; }
    }
}
