//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lichHoc
    {
        public int Id { get; set; }
        public string mssv { get; set; }
        public string monHoc { get; set; }
        public string lopHocPhan { get; set; }
        public string maHocPhan { get; set; }
        public string caHoc { get; set; }
        public string ngayHoc { get; set; }
        public string diaDiem { get; set; }
        public string giaoVien { get; set; }
    }
}
