//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class webapiEntities : DbContext
    {
        public webapiEntities()
            : base("name=webapiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bangDiemChiTiet> bangDiemChiTiets { get; set; }
        public virtual DbSet<chungChi> chungChis { get; set; }
        public virtual DbSet<danhSachKhoanPhaiDong> danhSachKhoanPhaiDongs { get; set; }
        public virtual DbSet<diemTrungBinhHocTap> diemTrungBinhHocTaps { get; set; }
        public virtual DbSet<lePhihocPhi> lePhihocPhis { get; set; }
        public virtual DbSet<lichHoc> lichHocs { get; set; }
        public virtual DbSet<sinhVien> sinhViens { get; set; }
        public virtual DbSet<thoigiandiadiem> thoigiandiadiems { get; set; }
        public virtual DbSet<thongBao> thongBaos { get; set; }
        public virtual DbSet<xuLyHocVu> xuLyHocVus { get; set; }
    }
}
