//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sinhVien
    {
        public int Id { get; set; }
        public string hoDem { get; set; }
        public string ten { get; set; }
        public string gioiTinh { get; set; }
        public string cmtnd { get; set; }
        public string ngaySinh { get; set; }
        public string noiSinh { get; set; }
        public string queQuan { get; set; }
        public string hocKyNhapHoc { get; set; }
        public string tinh { get; set; }
        public string huyen { get; set; }
        public string xa { get; set; }
        public string danToc { get; set; }
        public string quocTich { get; set; }
        public string sdt { get; set; }
        public string email { get; set; }
        public string mssv { get; set; }
        public string userName { get; set; }
        public string passWord { get; set; }
        public string khoa { get; set; }
        public string nganh { get; set; }
        public string lop { get; set; }
    }
}
