//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class thoigiandiadiem
    {
        public int id { get; set; }
        public string monhoc { get; set; }
        public string ca { get; set; }
        public string thu { get; set; }
        public string tu { get; set; }
        public string den { get; set; }
        public string diadiem { get; set; }
    }
}
